### PR TITLE
[WIP Do not merge] Add git ahead and behind indicators

### PR DESCRIPTION
**Pull request by Flygrounder**
I want to add git indicators for ahead and behind. At the moment they look like on the screenshot. Currently they are displayed even if there are no commits ahead and behind - this behavior needs to be fixed. Also I know, that with dirty check you make some optimizations and this currently runs `git status` on each redraw.

Want to hear your feedback on how you think it should look and behave.

2020-10-29-123448_1920x1080_scrot

### CODE REVIEW

**Comment by Flygrounder** [comment]
Unfortunately, with conditional display of indicators I experience fish redraw bug. I think we can solve it by rendering and displaying the full status string, adding the appropriate number of spaces at the end

**Comment by mattgreen** [comment]
On my large repo for $WORK, I see runtimes of about 100ms for `git status --branch --porcelain`. The current latency for lucid right now hangs at ~15ms for the initial prompt display. As you know, part of lucid's appeal is its low latency, so we'll need a faster way to retrieve that information. 

As for the UI, it's looking good. If the local branch is behind 4 commits and ahead 0 commits, does it show that it is ahead 0? I'd expect it to omit the portion relating to the fact that it ahead by 0, since it doesn't add any information. (It appears that is the case in the code, but wanted to confirm.) Additionally, please make the feature able to be toggled off, and defaulted to off.

> I think we can solve it by rendering and displaying the full status string, adding the appropriate number of spaces at the end

Yep. You'll need to account for the fact that the local branch might be quite behind the remote branch: 3 commits, or 3000 commits. Probably safe to leave four digits worth for each of the ahead/behind.

**Comment by Flygrounder** [comment]
> If the local branch is behind 4 commits and ahead 0 commits, does it show that it is ahead 0? I'd expect it to omit the portion relating to the fact that it ahead by 0, since it doesn't add any information. (It appears that is the case in the code, but wanted to confirm.)

Yes, it works exactly how you described. And it causes this redraw bug (which I will hopefully fix soon). 

As for optimization, I haven't studied your async dirty check yet. Is it possible to use the same approach for extracting ahead/behind value?

**Comment by Flygrounder** [comment]
I've partially solved problem with re-rendering. I am rendering the whole status line and filling the rest of the line with spaces. The only problem is `string length` counts escape characters used for coloring as characters. Is there any cross-platform to remove all color sequences from a string?

**Comment by mattgreen** [comment]
> As for optimization, I haven't studied your async dirty check yet. Is it possible to use the same approach for extracting ahead/behind value?

Unlikely. The dirty/not dirty status of a repository only requires two states (dirty/not dirty), so it can be encoded in the process exit value. But the ahead/behind status would probably require more. You need some sort of way to tell the foreground process (which is rendering the prompt) what the result of the background process is. See the latter part of the README for more discussion.

> Is there any cross-platform way to remove all color sequences from a string?

Perhaps `sed`?

**Comment by Flygrounder** [comment]
Yeah, I've figured out `sed` expressions that seem to remove all color sequences. You can check it if you change `string repeat -n $spaces " "` to `string repeat -n $spaces "-"` - now it fills the whole status line like on the screenshot

2020-11-02-095124_1920x1080_scrot
.

**Comment by mattgreen** [comment]
Be careful with that approach: if users resize their terminal to be smaller, they'll get unexpected line breaks. I'd recommend reserving just enough space that you might need.

As previously mentioned, the bigger issue is retrieving the ahead/behind information asynchronously and relaying it to the main process.

**Comment by IlanCosman** [comment]
Tide has a [decoloring function](https://github.com/IlanCosman/tide/blob/main/functions/_tide_decolor.fish) that you might want to look at.

**Comment by Flygrounder** [comment]
@IlanCosman thanks for advice. But the main performance here is with `git status` usage on each redraw. We need to do this in the background and message status with some form of IPC that works on both Linux and Mac.

@mattgreen can we use Unix sockets here?

**Comment by mattgreen** [comment]
Sockets are a good idea for IPC, but the cross-section of UNIX tools that are available on BSD/macOS/Linux/WSL is...quite limited. Perhaps `nc` is in all of those? I'm not certain.

IMO, "It just works" is a big draw for lucid, as it doesn't require anything else, and runs quite fast on all of those with no tweaking.

**Comment by IlanCosman** [comment]
What's the reason we can't do most things in git the same way we do the dirty checks? E.g. we have some command that tells us the number of commits behind we are. Can't we just exit-code return that value to our main fish instance and then display it?

**Comment by mattgreen** [comment]
@IlanCosman you can do that. The catch is that whatever comes back needs to be encoded somehow as an integer between 0 and 255. In some monorepos, it is quite possible your branch can fall more than 255 commits behind. (In this particular case, you could make 255 represent an ambiguous value such as "many more" ala Gmail). Additionally, there are two values here: ahead and behind.

I've held off on suggesting some sort of cross-platform, non-disk-backed IPC mechanism to the fish maintainers, mostly because it is out-of-scope, they have plenty to do, and too similar to universal variables. 

For what we want to do, a page of shared memory per TTY, would be perfect, but there is no default-installed CLI utility that would let read/write to it. Linux has `/dev/shm` which is great, but other platforms have no analog, as `/tmp` is not guaranteed to be backed by RAM.

**Comment by Flygrounder** [comment]
> Perhaps `nc` is in all of those? I'm not certain.

Unfortunately, not all linux distros ship it by default. So yes, we are very limited in ways of IPC

**Comment by mattgreen** [comment]
Closing due to inactivity. Tide has this feature, so you may want to try it out.

**Pull request closed without merging**
